algoritmo "Média de idade"

var

nome1, nome2: caractere
idade1, idade2: inteiro
media: real

inicio

escreval ("Dados da primeira pessoa:")
escreva ("nome:")
leia (nome1)
escreva ("idade:")
leia (idade1)

escreval ("Dados da segunda pessoa:")
escreva ("nome:")
leia (nome2)
escreva ("idade:")
leia (idade2)

media <- (idade1 + idade2) /2
escreval ("A idade média de ",  nome1 ,  " e "  , nome2,  " eh de " ,  media,  " anos")

fimalgoritmo
